import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Aside from "@/components/layout/aside/Aside";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex w-full flex-1">
      <main className="flex-1 flex w-full">
        <Aside />
        <div className="flex-1 flex flex-col items-center">{children}</div>
      </main>
    </div>
  );
}
